frontend/client/package.json
frontend/client/src/components/ListOfCategories.js
frontend/client/src/functions/useFetch.js
frontend/client/src/state/state.js
frontend/client/src/views/categoriesView.js
frontend/client/yarn.lock

Set up a global state store and added a hook for fetching data

Matthew feldman

---

frontend/client/src/App.js
frontend/client/src/components/Header.js
frontend/client/src/views/landingView.js

refactored app with state globally

---

frontend/client/src/App.js
frontend/client/src/components/ListOfCategories.js
frontend/client/src/views/subCategoryView.js

begun building subcategory view

---

frontend/client/src/App.js
frontend/client/src/views/singleResourceView.js

creating component for single resource view

creating single resource component view

---

frontend/client/src/App.js
frontend/client/src/components/ListOfCategories.js
frontend/client/src/components/TabNavigator.js
frontend/client/src/views/singleResourceView.js
frontend/client/src/views/subCategoryView.js

Creating tab navigator component for sub category view component. Making dynamic routes for sub category and single resource views.

creating tab navigator component for sub category view component

---

frontend/client/src/App.js
frontend/client/src/components/ListOfResources.js
frontend/client/src/components/TabNavigator.js
frontend/client/src/views/singleResourceView.js
frontend/client/src/views/subCategoryView.js

sending up latest

---

frontend/client/src/App.js
frontend/client/src/components/ListOfResources.js
frontend/client/src/components/ResourceList.js
frontend/client/src/components/TabNavigator.js
frontend/client/src/functions/useFetch.js
frontend/client/src/functions/useFetchSingle.js
frontend/client/src/reducers/languageReducer.js
frontend/client/src/views/singleResourceView.js

resource list bug has been quashed :)

fixed resource list bug

---

frontend/client/src/components/ResourceList.js
frontend/client/src/views/singleResourceView.js

fixing errors with a return statement in list of single resources

fixed a non return error

---

frontend/client/src/components/ShelterNearestYou.js
frontend/client/src/views/categoriesView.js
frontend/client/src/views/subCategoryList.js
frontend/client/src/views/subCategoryView.js

…and CategoriesView successuflly refactored.

Refactored file structure to match Design Architecture 

---

frontend/client/src/components/searchBar.js

results not yet functional as links

completes search functionality

---

frontend/client/src/components/searchBar.js

links from search results now working

add links for search

---

frontend/client/src/App.js
frontend/client/src/components/ResourcesNearestYou.js
frontend/client/src/components/ShelterNearestYou.js
frontend/client/src/components/TabNavigator.js
frontend/client/src/views/singleResourceView.js
frontend/client/src/views/subCategoryList.js

Displays three closest of a resource when you enter a category

Resources nearest you is functioning

---

frontend/client/src/App.js
frontend/client/src/components/TabNavforSubView.js
frontend/client/src/components/TabNavigator.js
frontend/client/src/views/singleResourceView.js
frontend/client/src/views/subCategoryList.js

fixed all tab nav issues

---

frontend/client/src/components/ListOfCategories.js
frontend/client/src/components/ShelterNearestYou.js
frontend/client/src/views/categoriesView.js

styling fixes on categories view

fixed some styling

---

frontend/client/src/components/ShelterNearestYou.js

- Added marker and info window
- Added a function that opens a google maps query of the nearest resource in a new window
- Added an onClick to the View Map div

Shelter Nearest You Card:

---

frontend/client/_redirects

Trying to fix netlify crashes on refresh

---

frontend/client/src/views/singleResourceView.js

Added functions to switch between details and services when in single resource view

can now tab between details and services

---

frontend/client/src/App.js
frontend/client/src/components/SingleResource.js
frontend/client/src/views/singleResourceView.js

- Created component
- Added map and info
- Imported component to view

Single Resource Component 

---

frontend/client/src/components/BreadcrumbMainCat.js
frontend/client/src/components/ListOfCategories.js
frontend/client/src/components/TabNavigator.js

TabNav has images coming in for all, just needs to be styled

got images for tabnav

---

frontend/client/src/App.css
frontend/client/src/components/ListOfCategories.js
frontend/client/src/components/ShelterNearestYou.js
frontend/client/src/components/searchBar.js
frontend/client/src/views/categoriesView.js

Setting container on CategoryView to 1366px for desktop width, and resizing ListofCategories and ShelterNearestYou components to match dimensions.

Resizing CategoryView to 1366px Width

---

frontend/client/src/App.css
frontend/client/src/components/BreadcrumbMainCat.js
frontend/client/src/components/TabNavigator.js

added some more styling to tab nav

---

frontend/client/src/App.css
frontend/client/src/components/ListOfCategories.js
frontend/client/src/components/TabNavigator.js
frontend/client/src/index.css

Regex to make things look nicer

fixed strings coming in from the database, removing underscores

---

frontend/client/src/components/Header.js
frontend/client/src/views/landingView.js

Refactoring landingView CTA image to have responsive height, and changing link on Header logo to route to landingView.

making CTA image responsive and changing Header logo link to landingView

---

frontend/client/src/App.css
frontend/client/src/components/ResourcesNearestYou.js
frontend/client/src/components/SingleResource.js
frontend/client/src/views/singleResourceView.js

-  Added styles to single resource card based on design specs
- Merged updates from master

Single Resource View Styling:

---

frontend/client/src/App.css
frontend/client/src/components/LandingSearchBar.js
frontend/client/src/components/ShelterNearestYou.js
frontend/client/src/views/landingView.js

Creating LandingSearchBar component for search input in LandingView and styling according to design. Fixed box shadowing on SheltersNearestYou component.

creating LandingSearchBar component and refactoring styling

---

frontend/client/src/App.css
frontend/client/src/components/TabNavigator.js
frontend/client/src/components/searchBar.js

Styling in modal, making it look nicer

stylings added to modal

---

frontend/client/src/components/ShelterNearestYou.js

Margins still need to be adjusted and ViewDetails and ViewMap buttons need to be styled.

styling ShelterNearestYou component

---

frontend/client/src/components/Header.js
frontend/client/src/components/ListOfCategories.js
frontend/client/src/components/ShelterNearestYou.js

Tablet view for categories view completed

category view tablet view is done

---

frontend/client/src/components/Footer.js
frontend/client/src/components/Header.js
frontend/client/src/components/ListOfCategories.js
frontend/client/src/components/ShelterNearestYou.js
frontend/client/src/views/categoriesView.js

added styling in categories view for mobile, should be fully responsive

stylings for categories view mobile

---

frontend/client/src/components/ResourcesNearestYou.js
frontend/client/src/components/TabNavforSubView.js

Styled for tabnav in the sub and detail view are set up and looks good

tabnavsubview looks good

---

frontend/client/src/components/Footer.js
frontend/client/src/components/LandingSearchBar.js
frontend/client/src/views/landingView.js

Removing search button in tablet and mobile views and making navbar more responsive.

refactoring LandingView

---

frontend/client/src/components/LandingSearchBar.js
frontend/client/src/components/ShelterNearestYou.js
frontend/client/src/components/ViewDetailsButton.js
frontend/client/src/views/landingView.js

Adding letter-spacing to LandingView and ShelterNearestYou, and refactoring ShelterNearestYou for colors, font-size and margin as well.

refactoring ShelterNearestYou and LandingView

---

frontend/client/src/components/Header.js
frontend/client/src/components/searchBar.js

Some refactoring of search and header component to make search bar more responsive

adjusted searchbar so it is always in the center of the screen

---

frontend/client/src/App.css
frontend/client/src/components/TabNavigator.js

* id for domestic violence to stretch text properly in container
* id for women and rehab subcat in health_care to set wrap at proper distance
adds new if statement to differentiate women in shelter main cat from women in healthcare maincat

adds ids to correct styling on breadcrumbs

---

frontend/client/src/components/searchBar.js

*takes out the on click that is making the search close across all screens

retros a close for search to make main search functional again

---

frontend/client/package.json
frontend/client/src/components/LandingSearchBar.spec.js
frontend/client/src/components/__snapshots__/LandingSearchBar.spec.js.snap
frontend/client/yarn.lock

Testing began to be added. Need to research more on testing routes

started adding testing

---

frontend/client/src/App.css
frontend/client/src/components/Footer.js
frontend/client/src/components/Header.js
frontend/client/src/components/LandingSearchBar.js
frontend/client/src/components/ResourcesNearestYou.js
frontend/client/src/components/ShelterNearestYou.js
frontend/client/src/components/searchBar.js
frontend/client/src/views/landingView.js

Adjusting Landing View heading, logo subscript and search input text. Adjusting Header height and search bar text. Adjusting Footer text and padding. Adjusting left padding and font-weight on Shelter Nearest You component. Adjusting font-weight on Resources Nearest You card.

Making styling changes to match design specs more closely

---

frontend/client/src/components/ResourcesNearestYou.js
frontend/client/src/components/SingleResource.js

- Fixed outreach services single reource bug
- Added error handing to resources nearest you to prevent undefines

Styling on Outreach services and bugs

---

frontend/client/src/App.css
frontend/client/src/components/BreadcrumbMainCat.js
frontend/client/src/components/TabNavigator.js

Moves MainCatBtnCont to BreadcrumbMainCat as StyledCont

adds styling continuity per design direction. 

---

frontend/client/package.json
frontend/client/src/App.js
frontend/client/src/App.test.js
frontend/client/yarn.lock

testing to make sure views render

finished testing in app.js

---

frontend/client/src/App.css
frontend/client/src/views/landingView.js

Modal know is more center with an overlay

Language Modal fixes with modal

---

frontend/client/src/App.css

made the cursor be a pointer when on the x

---

frontend/client/src/components/ShelterNearestYou.js
frontend/client/src/components/SingleResource.js

changing Single Resource to show unavailable if resource is loading or not available

---

frontend/client/src/components/Footer.js
frontend/client/src/components/Header.js
frontend/client/src/components/HitComponent.js
frontend/client/src/components/LandingSearchBar.js
frontend/client/src/components/ListOfCategories.js
frontend/client/src/components/searchBar.js

Added some comments

---

frontend/client/src/components/ResourceList.js
frontend/client/src/components/ResourcesNearestYou.js
frontend/client/src/components/searchBar.js

Comments in ResourceList, ResourceNearestYou, searchBar

Finished commenting most of the code
